import type { Brief } from './types';

export const sampleBrief: Brief = {
  id: 'demo-brief-2026-05-16',
  date: '2026-05-16',
  title: 'Morning Intelligence Brief',
  executiveSummary: 'Demo brief using example data. Production briefs are generated only from cited public sources retrieved at runtime; uncited claims are excluded by the citation checker.',
  overallThreatScore: 3.6,
  generatedAt: new Date().toISOString(),
  topDevelopments: [
    { id:'dev-1', title:'NATO readiness and deterrence remain central to European security planning', region:'Europe', factualSummary:'This demo item illustrates how NATO-related public reporting is summarized with direct citations in production.', analysis:'Analytical assessment is separated from reported facts and scored using the transparent model.', whyItMatters:'NATO posture affects deterrence, defense budgets, and U.S. foreign policy commitments.', whatToWatch:['Official NATO communiqués','Defense ministry budget announcements','Border incident reporting'], citations:[{title:'NATO Newsroom', outlet:'NATO', url:'https://www.nato.int/cps/en/natohq/news.htm'}], threat:{score:4,label:'High', explanation:'High diplomatic and U.S. policy relevance; escalation score depends on verified current reporting.', factors:{militaryEscalation:4,economicImpact:2,diplomaticImportance:5,humanitarianImpact:3,usForeignPolicyRelevance:5}}},
    { id:'dev-2', title:'Taiwan Strait activity monitored for escalation indicators', region:'Indo-Pacific', factualSummary:'This demo item shows the Taiwan workflow; production uses public government and reputable media sources.', analysis:'Military activity near Taiwan can affect regional deterrence and global supply chains.', whyItMatters:'Taiwan Strait stability is linked to U.S.-China relations and semiconductor supply-chain risk.', whatToWatch:['Defense ministry statements','Shipping and aviation advisories','U.S. and allied diplomatic messaging'], citations:[{title:'Taiwan Ministry of National Defense News', outlet:'MND', url:'https://www.mnd.gov.tw/english/'}], threat:{score:4,label:'High', explanation:'High military and economic relevance due to regional escalation pathways.', factors:{militaryEscalation:5,economicImpact:4,diplomaticImportance:5,humanitarianImpact:3,usForeignPolicyRelevance:5}}},
    { id:'dev-3', title:'Energy security remains a pressure point in sanctions and conflict policy', region:'Global', factualSummary:'This demo item illustrates energy-security analysis sourced from public reporting and official agencies.', analysis:'Energy disruptions can translate quickly into economic pressure and diplomatic bargaining.', whyItMatters:'Energy prices shape sanctions durability, domestic politics, and alliance coordination.', whatToWatch:['IEA market updates','Sanctions announcements','Shipping chokepoint disruption'], citations:[{title:'IEA News', outlet:'International Energy Agency', url:'https://www.iea.org/news'}], threat:{score:3,label:'Moderate', explanation:'Moderate-to-high economic impact; military risk depends on the trigger event.', factors:{militaryEscalation:2,economicImpact:5,diplomaticImportance:4,humanitarianImpact:3,usForeignPolicyRelevance:4}}},
    { id:'dev-4', title:'Cyber operations and election security require attribution caution', region:'Global', factualSummary:'Production briefs avoid unverified social media and label attribution uncertainty clearly.', analysis:'Cyber incidents can have high policy salience even when public evidence is incomplete.', whyItMatters:'Election interference and infrastructure attacks can produce sanctions, indictments, or retaliation debates.', whatToWatch:['CISA advisories','CERT reports','Official attribution statements'], citations:[{title:'CISA Cybersecurity Advisories', outlet:'CISA', url:'https://www.cisa.gov/news-events/cybersecurity-advisories'}], threat:{score:3,label:'Moderate', explanation:'Potential high impact, but score is constrained until attribution and damage are verified.', factors:{militaryEscalation:2,economicImpact:4,diplomaticImportance:4,humanitarianImpact:2,usForeignPolicyRelevance:4}}},
    { id:'dev-5', title:'Middle East diplomatic and conflict indicators tracked separately', region:'Middle East', factualSummary:'This demo item shows regional monitoring; production includes citations from public outlets and official sources.', analysis:'The region can shift quickly between diplomacy, proxy activity, and humanitarian crisis.', whyItMatters:'Developments may affect U.S. diplomacy, energy markets, regional security, and humanitarian operations.', whatToWatch:['Ceasefire negotiations','Humanitarian access reports','Regional military alerts'], citations:[{title:'UN News Middle East', outlet:'United Nations', url:'https://news.un.org/en/news/region/middle-east'}], threat:{score:4,label:'High', explanation:'Humanitarian and diplomatic stakes often elevate the threat score.', factors:{militaryEscalation:4,economicImpact:3,diplomaticImportance:4,humanitarianImpact:5,usForeignPolicyRelevance:4}}}
  ],
  regionUpdates: { Europe:['NATO and Ukraine-related developments prioritized when verified.'], 'Middle East':['Conflict, humanitarian access, and diplomacy monitored with citation requirements.'], 'Indo-Pacific':['China, Taiwan, and maritime security indicators tracked.'], Americas:['U.S. foreign policy, elections, and sanctions monitored.'], Africa:['Coups, conflict, elections, and energy/security partnerships monitored.'], Global:['Cyber, energy, sanctions, and multilateral diplomacy tracked across regions.'] },
  sources: []
};
sampleBrief.sources = sampleBrief.topDevelopments.flatMap(d => d.citations);
